import type { IconType } from "react-icons";
import { FaJava } from "react-icons/fa6";
import {
  SiAnthropic,
  SiBun,
  SiC,
  SiClickhouse,
  SiDocker,
  SiDrizzle,
  SiExpress,
  SiFastify,
  SiGit,
  SiGo,
  SiGooglegemini,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiReact,
  SiRedis,
  SiSanity,
  SiTailwindcss,
  SiTldraw,
  SiTypescript,
  SiVercel,
} from "react-icons/si";

type Technology = { icon?: IconType; logoSrc?: string };

/** Local logoSrc overrides the bundled icon. Paths are relative to public/. */
export const TECHNOLOGIES: Record<string, Technology> = {
  React: { icon: SiReact },
  "React.js": { icon: SiReact },
  "Next.js": { icon: SiNextdotjs },
  "Next.js 15+": { icon: SiNextdotjs },
  TypeScript: { icon: SiTypescript },
  "Tailwind CSS": { icon: SiTailwindcss },
  "Node.js": { icon: SiNodedotjs },
  Bun: { icon: SiBun },
  "Express.js": { icon: SiExpress },
  Fastify: { icon: SiFastify },
  PostgreSQL: { icon: SiPostgresql },
  "Drizzle ORM": { icon: SiDrizzle },
  ClickHouse: { icon: SiClickhouse },
  Redis: { icon: SiRedis },
  MongoDB: { icon: SiMongodb },
  "Sanity CMS": { icon: SiSanity },
  "Google Gemini API": { icon: SiGooglegemini },
  "Google Gemini AI": { icon: SiGooglegemini },
  "Gemini 1.5 Pro": { icon: SiGooglegemini },
  "Anthropic Claude API": { icon: SiAnthropic },
  Vercel: { icon: SiVercel },
  Docker: { icon: SiDocker },
  "Git / GitHub": { icon: SiGit },
  Postman: { icon: SiPostman },
  Go: { icon: SiGo },
  Python: { icon: SiPython },
  Java: { icon: FaJava },
  C: { icon: SiC },
  npm: { icon: SiNpm },
  tldraw: { icon: SiTldraw },
  // No matching marks in the installed icon set. Add a local SVG here later.
  "Framer Motion": {},
  Zustand: {},
  "Vercel AI SDK": {},
  // Protocols and concepts have no single brand logo; keep their text labels.
  "RESTful APIs": {},
  WebSocket: {},
  PTY: {},
};
